image:
  - Visual Studio 2022
  - Ubuntu

version: 5.0.0-b{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run -p:LEGACYCI=true -c:Release --project test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build_with_packaging.bat --legacyci

    artifacts:
      - path: .\.dist\*.nupkg
