image:
  - Visual Studio 2022
  - Ubuntu

version: 5.0.0-b{build}

test: off

skip_commits:
  message: /noci .*/

build_script:
  - dotnet run -p:LatestNet=net7.0 -p:GeneratePackageOnBuild=false -c:Release --project test/FastExpressionCompiler.TestsRunner/FastExpressionCompiler.TestsRunner.csproj

for:
  - matrix:
      only:
        - image: Visual Studio 2022

    build_script:
      - build.bat net8.0

    artifacts:
      - path: .\.dist\*.nupkg
